### ISSUE TITLE
cnx-easybake 1.2.1 is not available for python 3

### ISSUE THREAD

**Issue by karenc** [openstax/cnx-easybake#104]
The files available for cnx-easybake 1.2.1 on pypi https://pypi.org/project/cnx-easybake/1.2.1/#files only has a wheel file for python 2.  When I try to install it on python 3, I get [this error](https://travis-ci.org/openstax/nebuchadnezzar/builds/505793888#L465):

```
Collecting cnx-easybake>=1.2.1 (from -r requirements/main.txt (line 2))
  Could not find a version that satisfies the requirement cnx-easybake>=1.2.1 (from -r requirements/main.txt (line 2)) (from versions: 0.6.0, 1.1.0, 1.2.0)
```

This is blocking the baked pdf CLI `neb bake` openstax/nebuchadnezzar#137

**Comment by karenc** [comment]
@tomjw64 and @pumazi Do you know if cnx-easybake is released to pypi using Jenkins?  I checked the [Jenkinsfile](https://github.com/openstax/cnx-easybake/blob/master/Jenkinsfile#L15) and it looks like it should've created a universal `--universal` wheel file.

**Comment by pumazi** [comment]
Corrected. The tag was created on a branch. A re-release has been made as `1.2.2`
