### ISSUE TITLE
Counter increments don't fire before counter() calls

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-easybake#29]
Counter increments should always fire before counter() calls when they are declarations for selectors that select the same element. For example, in browser for the HTML
```
<div>
    <p>This is some text.</p>
  </div>
```
the CSS 
```
div p::before {
  content: counter(c);
}
p {
  counter-increment: c;
}
```
 and
```
p::before {
  content: counter(c);
}
div p {
  counter-increment: c;
}
```
both produce the final output of `1This is some text.`

However, CSS into easybake
```
div p {
  content: counter(c);
}
p {
  counter-increment: c;
}
```
 will produce an output of `1`
```
p {
  content: counter(c);
}
div p {
  counter-increment: c;
}
```
 will produce an output of `0`

**Comment by reedstrm** [comment]
Note that the  browser example CSS _will_ produce the same result in easybake, since psuedo-element selectors are processed _after_ direct selectors. The problem as presented is one of selectivity, actually. The problem as described in the title is actually that:
```
p {
counter-increment: c;
content: counter(c):
}
```
and 
```
p {
content: counter(c);
counter-increment: c
}
```
Should, according to the spec, provide the same result.

**Comment by reedstrm** [comment]
This can be solved in the code by restructuring how the internal modification commands are build, for a given set of declarations under one selector. Rather than evaluation immediately, need insert a look-it-up command in the stack.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
