### ISSUE TITLE
How could css_to_func be improved?

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-easybake#58]
I was trying to change the `attr-group-by: first-letter(content());` definitions to be `string-set: group-by first-letter(content());`  because the `group-by="a"` attribute is not needed in the baked HTML.

I tried replacing `group-by: span, "span::attr(group-by)", nocase;` with `group-by: span, "span::string(group-by)", nocase;` thinking that would work (since both `attr()` and `string()` are defined functions which led me to `css_to_func`.

Could/should `span::string(group-by)` be allowed, and if so, could it be a 1st-class selector?

Anywho, just thought I'd post to remember to revisit when folks get back from the Holidays ☃️ 

[Example Source](https://github.com/Connexions/cnx-recipes/compare/experiment-group-by-as-a-string)

**Comment by philschatz** [comment]
Aha! `group-by: span, "span::string(group-by)", nocase;` ends up constructing XPath and xpath does not know about string/counter values. 

But what if it did know about those?

Currently the state is stored in data structures outside of the DOM but what if we created/updated special attributes which stored the string/counter information?


So, something like `div { string-set: NAME "VALUE"; }` would cause this to be in the DOM: `<div _string_NAME="VALUE" >...`,  that way XPath could still be used?

**Comment by reedstrm** [comment]
The correct spelling of that is, I think, `span::first-letter()` since that pseudo-element is defined to be the first letter of the content

**Comment by reedstrm** [comment]
so `group-by: span, span::first-letter()` for completeness

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
