### ISSUE TITLE
Non-zero exit status when exception occurs

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-easybake#61]
When an exception occurs in `cnx-easybake` a stack trace is generated but it seems like a 0 exit status is returned. If it returned a non-zero exit status other scripts would be able to handle when baking fails.

My bash-foo could be faulty though; see https://github.com/Connexions/cnx-recipes/pull/146

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
