### ISSUE TITLE
Disallow `<script>` and on*="..." attributes

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-easybake#68]
For security reasons. Also, maybe have a white/black-list for elements like `<marquee>` and `<phils-non-html-element>`

refs Connexions/cnx-rulesets#171, [Trello](https://trello.com/c/bIqKEK1W/15-cte-webview1-01-update-webview-design-to-ensure-usability)

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
